// Nav scroll
const nav = document.getElementById('navbar');
window.addEventListener('scroll', () => {
    nav.classList.toggle('scrolled', window.scrollY > 50);
});

// Intersection Observer for animations
const observer = new IntersectionObserver((entries) => {
    entries.forEach(e => {
        if (e.isIntersecting) {
            e.target.classList.add('visible');
            observer.unobserve(e.target);
        }
    });
}, { threshold: 0.12 });
document.querySelectorAll('.fade-in').forEach(el => observer.observe(el));

// Counter animation
let countersStarted = false;
const counters = document.querySelectorAll('.stat-num[data-target]');

const runCounters = () => {
    counters.forEach(el => {
        const target = +el.getAttribute('data-target');
        const isKm = el.classList.contains('counter-km');
        const isPct = el.classList.contains('counter-pct');
        const duration = 1800;
        const steps = 60;
        const inc = target / steps;
        let current = 0;
        const suffix = isPct ? '%' : (isKm ? ' км' : '+');
        const timer = setInterval(() => {
            current = Math.min(current + inc, target);
            el.textContent = Math.floor(current) + suffix;
            if (current >= target) clearInterval(timer);
        }, duration / steps);
    });
};

const statsBar = document.querySelector('.stats-bar');
const statsObserver = new IntersectionObserver((entries) => {
    if (entries[0].isIntersecting && !countersStarted) {
        countersStarted = true;
        runCounters();
    }
}, { threshold: 0.4 });
if (statsBar) statsObserver.observe(statsBar);

// ===== TRANSLATIONS =====
const translations = {
    ru: {
        nav_about: 'О компании',
        nav_services: 'Услуги',
        nav_projects: 'Проекты',
        nav_partner: 'Партнёрство',
        nav_why: 'Преимущества',
        nav_contact: 'Связаться',
        nav_contact_footer: 'Контакты',
        hero_badge: 'Казахстан · Все виды лицензий',
        hero_title: 'Надёжный партнёр в сфере<br><em>телекоммуникаций</em> и<br>инфраструктурного строительства',
        hero_sub: 'проверенный подрядчик крупнейших телекоммуникационных операторов Казахстана. Строительство ВОЛС, развёртывание инфраструктуры и объекты под ключ.',
        hero_location: 'г. Астана, Казахстан',
        hero_licenses: 'СМР 1 кат. · Проектирование 1 кат. · Изыскания',
        hero_partner: 'Партнёр АО Казахтелеком',
        hero_btn_projects: 'Наши проекты',
        hero_btn_contact: 'Связаться',
        stat1: 'Единиц спецтехники',
        stat2: 'Профессионалов',
        stat3: 'Км ВОЛС по проекту SWAP',
        stat4: '% рынка — доля Казахтелеком',
        about_label: 'О компании',
        about_title: 'ITStroyService — надёжный подрядчик в сфере телекоммуникаций',
        about_p1: 'Компания специализируется на строительстве и развитии телекоммуникационной инфраструктуры, а также на инфраструктурном и специализированном строительстве в Республике Казахстан.',
        about_p2: 'Мы являемся надёжным подрядчиком для крупнейших телекоммуникационных операторов страны.',
        feat1_title: 'Телекоммуникации',
        feat1_desc: 'Строительство ВОЛС, развёртывание инфраструктуры, подключение сетей',
        feat2_title: 'Строительство',
        feat2_desc: 'Инфраструктурное строительство, работы под ключ, проектирование',
        feat3_title: 'Обслуживание',
        feat3_desc: 'Модернизация сетей, техническое обслуживание, ремонт',
        feat4_title: 'Лицензии',
        feat4_desc: 'СМР 1 кат., Проектирование 1 кат., Изыскания — все необходимые допуски',
        resources_label: 'Ресурсы компании',
        res1: 'Спецтехника',
        res1_unit: 'единиц',
        res2: 'Специалисты',
        res2_unit: 'человек',
        res3: 'Экскаваторы, кабелеукладчики, бульдозеры, тралы, пикапы',
        res3_val: 'и другое',
        res4: 'Ключевой клиент',
        res5: 'Лицензии',
        res5_val: 'СМР 1 кат.<br>Проектирование 1 кат.<br>Изыскания',
        svc_label: 'Направления деятельности',
        svc_title: 'Полный спектр услуг',
        svc_desc: 'Два основных направления — телекоммуникации и инфраструктурное строительство — покрывают весь цикл проекта от проектирования до сдачи.',
        svc1_title: 'Телекоммуникации и связь',
        svc1_li1: 'Строительство и развитие волоконно-оптических линий связи (ВОЛС) любой сложности',
        svc1_li2: 'Развёртывание телекоммуникационной инфраструктуры под ключ',
        svc1_li3: 'Подключение корпоративных и операторских сетей',
        svc1_li4: 'Обслуживание и модернизация сетей связи',
        svc2_title: 'Инфраструктурное строительство',
        svc2_li1: 'Строительство объектов телекоммуникационной отрасли',
        svc2_li2: 'Дорожное и инфраструктурное строительство',
        svc2_li3: 'Проектирование, монтаж и ввод объектов в эксплуатацию',
        svc2_li4: 'Работы «под ключ» — ПИР + СМР, все виды лицензий',
        proj_label: 'Выполненные проекты',
        proj_title: 'Масштабные работы<br>для Казахтелеком',
        proj_key: 'Ключевой проект',
        proj_client: 'Заказчик:',
        proj_desc: 'Проект реализован в рамках программы SWAP для крупнейшего телекоммуникационного оператора Казахстана — АО Казахтелеком.',
        m1: 'Общая протяжённость ВОЛС',
        m2: 'Магистральная сеть',
        m3: 'Распределительная сеть',
        m4: 'Установленные опоры',
        m5: 'Муфты',
        m6: 'ОРК',
        proj_result: '<strong>Проект успешно завершён в установленные сроки</strong> с высоким качеством выполненных работ, что подтверждает профессионализм и надёжность компании.',
        op1_title: 'Капитальный ремонт АО Казахтелеком',
        op1_desc: 'Полный комплекс капитального ремонта помещений по адресу: г. Алматы, ул. Панфилова, 129. Включая отделочные работы, замену инженерных систем и модернизацию.',
        op1_tag: 'Заказчик: АО Казахтелеком',
        op2_title: 'Широкий спектр работ',
        op2_desc: 'Многолетний опыт работы с крупнейшими телеком-операторами Казахстана. Работы выполнены в соответствии со всеми строительными нормами и стандартами.',
        op2_tag: 'Все виды строительства',
        op3_title: 'Гибкий подход',
        op3_desc: 'Гибкий подход к требованиям заказчика. Работы выполняются в строгом соответствии с требованиями и стандартами каждого клиента.',
        op3_tag: 'Под ключ',
        trends_label: 'Рынок телекоммуникаций',
        trends_title: 'Тренды развития отрасли ВОЛС',
        trends_desc: 'Масштаб и перспективы рынка Казахстана открывают широкие возможности для дальнейшего роста.',
        trend1_title: 'Технология GPON',
        trend1_desc: 'Переход на технологию GPON (Gigabit Passive Optical Network) для высокоскоростного доступа к интернету.',
        trend1_adv: 'Преимущества:',
        trend1_li1: 'Скорость до 1 Гбит/с',
        trend1_li2: 'Меньшее количество активного оборудования',
        trend1_li3: 'Снижение затрат на обслуживание',
        bsc_txt: 'домохозяйств уже имеют техническую возможность подключения к GPON в Казахстане',
        trend2_title: 'Увеличение пропускной способности',
        trend2_desc: 'Модернизация существующих сетей с увеличением пропускной способности до 400–800 Гбит/с и выше.',
        trend2_fut: 'Будущее:',
        trend2_li1: 'Переход к 1.2–1.6 Тбит/с',
        trend2_li2: 'Поддержка облачных сервисов',
        trend2_li3: 'Инфраструктура для ИИ и Big Data',
        ftth_desc: 'Активное развитие сетей FTTH (Fiber to the Home) — волокно до дома для обеспечения высокоскоростного доступа.',
        partner_label: 'Ключевое партнёрство',
        partner_title: 'Партнёрство с Казахтелеком',
        partner_desc: 'Крупнейший телеком-оператор Казахстана. Казахтелеком — компания с самыми строгими стандартами качества и контроля выполнения работ.',
        pkpi1: 'Доля рынка',
        pkpi2: 'Млн абонентов',
        pkpi3: 'В стране',
        why_choose: 'Почему выбирают нас:',
        pr1_title: 'Высочайшие требования к качеству',
        pr1_desc: 'Казахтелеком применяет строжайшие стандарты качества и контроля — наши работы соответствуют им в полной мере.',
        pr2_title: 'Доверие лидера',
        pr2_desc: 'Партнёрство с Казахтелеком — лучшее подтверждение нашего профессионализма и надёжности как подрядчика.',
        pr3_title: 'Соблюдение сроков',
        pr3_desc: 'Успешная реализация крупных проектов в установленные сроки — проект SWAP тому подтверждение.',
        pr4_title: 'Надёжность и профессионализм',
        pr4_desc: 'Многолетнее партнёрство подтверждает нашу надёжность как проверенного подрядчика.',
        why_label: 'Преимущества партнёрства',
        why_title: 'Почему ITStroyService?',
        why_desc: 'Шесть ключевых причин, почему ведущие операторы Казахстана выбирают нас в качестве подрядчика.',
        why1_title: 'Современное оборудование',
        why1_desc: 'Спецтехника последнего поколения и современный автопарк для эффективного выполнения работ любой сложности.',
        why2_title: 'Проверенный опыт',
        why2_desc: 'Успешная реализация крупных проектов для Казахтелеком, включая проект SWAP с объёмом работ 692 км ВОЛС.',
        why3_title: 'Все лицензии',
        why3_desc: 'Все необходимые лицензии для выполнения телекоммуникационных и строительных работ (СМР 1 кат., Проектирование 1 кат., Изыскания).',
        why4_title: 'Квалифицированная команда',
        why4_desc: '100+ профессиональных специалистов с многолетним опытом работы в телекоммуникационной отрасли.',
        why5_title: 'Полный цикл услуг',
        why5_desc: 'От проектирования до ввода в эксплуатацию — полный комплекс работ «под ключ» (ПИР + СМР).',
        why6_title: 'Конкурентные цены',
        why6_desc: 'Оптимальное соотношение цены и качества при соблюдении всех технических требований заказчика.',
        contact_label: 'Контакты',
        contact_title: 'Готовы к сотрудничеству',
        contact_desc: 'ITStroyService — ваш надёжный партнёр в развитии телекоммуникационной инфраструктуры.',
        c_addr_lbl: 'Адрес',
        c_addr: 'г. Астана, Казахстан',
        c_email: 'Указан в договоре',
        c_lic_lbl: 'Лицензии',
        c_lic: 'СМР 1 кат. · Проектирование 1 кат. · Изыскания',
        ch_title: 'Единый подрядчик для сложных задач',
        ch_desc: 'Объединяем физическую инфраструктуру и цифровые технологии. Работаем в соответствии с высочайшими стандартами качества.',
        cp1: 'Строительство ВОЛС любой сложности',
        cp2: 'Развёртывание телекоммуникационной инфраструктуры',
        cp3: 'Работы «под ключ» — ПИР + СМР',
        cp4: 'Капитальный ремонт объектов',
        cp5: 'Дорожное и инфраструктурное строительство',
        cp6: 'Обслуживание и модернизация сетей',
        footer_copy: '© 2025 ITStroyService. Все права защищены. Казахстан.',
    },

    kz: {
        nav_about: 'Компания туралы',
        nav_services: 'Қызметтер',
        nav_projects: 'Жобалар',
        nav_partner: 'Серіктестік',
        nav_why: 'Артықшылықтар',
        nav_contact: 'Байланыс',
        nav_contact_footer: 'Байланыс',
        hero_badge: 'Қазақстан · Барлық лицензиялар',
        hero_title: '<em>Телекоммуникация</em> және<br>инфрақұрылымдық құрылыс<br>саласындағы сенімді серіктес',
        hero_sub: 'Қазақстанның ірі телекоммуникациялық операторларының сыналған мердігері. ТОЖС құрылысы, инфрақұрылымды орналастыру және кілттік объектілер.',
        hero_location: 'Астана қ., Қазақстан',
        hero_licenses: 'ҚСЖ 1 кат. · Жобалау 1 кат. · Іздестіру',
        hero_partner: 'Қазақтелеком АҚ серіктесі',
        hero_btn_projects: 'Біздің жобалар',
        hero_btn_contact: 'Байланысу',
        stat1: 'Арнайы техника бірлігі',
        stat2: 'Мамандар',
        stat3: 'SWAP жобасы бойынша ТОЖС км',
        stat4: '% нарық — Қазақтелеком үлесі',
        about_label: 'Компания туралы',
        about_title: 'ITStroyService — телекоммуникация саласының сенімді мердігері',
        about_p1: 'Компания Қазақстан Республикасындағы телекоммуникациялық инфрақұрылымды салу мен дамытуға, сондай-ақ инфрақұрылымдық және мамандандырылған құрылысқа маманданған.',
        about_p2: 'Біз Қазақстанның ірі телекоммуникациялық операторлары үшін сенімді мердігерміз.',
        feat1_title: 'Телекоммуникация',
        feat1_desc: 'ТОЖС құрылысы, инфрақұрылымды орналастыру, желіге қосу',
        feat2_title: 'Құрылыс',
        feat2_desc: 'Инфрақұрылымдық құрылыс, кілттік жұмыстар, жобалау',
        feat3_title: 'Қызмет көрсету',
        feat3_desc: 'Желілерді жаңарту, техникалық қызмет көрсету, жөндеу',
        feat4_title: 'Лицензиялар',
        feat4_desc: 'ҚСЖ 1 кат., Жобалау 1 кат., Іздестіру — барлық рұқсаттар',
        resources_label: 'Компания ресурстары',
        res1: 'Арнайы техника',
        res1_unit: 'бірлік',
        res2: 'Мамандар',
        res2_unit: 'адам',
        res3: 'Экскаватор, кабель салушы, бульдозер, трал, пикап',
        res3_val: 'және т.б.',
        res4: 'Негізгі клиент',
        res5: 'Лицензиялар',
        res5_val: 'ҚСЖ 1 кат.<br>Жобалау 1 кат.<br>Іздестіру',
        svc_label: 'Қызмет бағыттары',
        svc_title: 'Толық қызмет кешені',
        svc_desc: 'Екі негізгі бағыт — телекоммуникация және инфрақұрылымдық құрылыс — жобалаудан тапсырысқа дейінгі толық циклді қамтиды.',
        svc1_title: 'Телекоммуникация және байланыс',
        svc1_li1: 'Кез келген күрделіліктегі талшықты-оптикалық байланыс желілерін (ТОЖС) салу және дамыту',
        svc1_li2: 'Телекоммуникациялық инфрақұрылымды кілт тапсыру принципімен орналастыру',
        svc1_li3: 'Корпоративтік және операторлық желілерді қосу',
        svc1_li4: 'Байланыс желілеріне қызмет көрсету және жаңарту',
        svc2_title: 'Инфрақұрылымдық құрылыс',
        svc2_li1: 'Телекоммуникациялық сала объектілерін салу',
        svc2_li2: 'Жол және инфрақұрылымдық құрылыс',
        svc2_li3: 'Объектілерді жобалау, монтаждау және пайдалануға беру',
        svc2_li4: '«Кілт тапсыру» принципімен жұмыс — ЖЖЖ + ҚСЖ, барлық лицензиялар',
        proj_label: 'Орындалған жобалар',
        proj_title: 'Қазақтелеком үшін<br>ауқымды жұмыстар',
        proj_key: 'Негізгі жоба',
        proj_client: 'Тапсырыс беруші:',
        proj_desc: 'Жоба Қазақстанның ірі телекоммуникациялық операторы — Қазақтелеком АҚ үшін SWAP бағдарламасы аясында іске асырылды.',
        m1: 'ТОЖС жалпы ұзындығы',
        m2: 'Магистральдық желі',
        m3: 'Таратушы желі',
        m4: 'Орнатылған тіреулер',
        m5: 'Муфталар',
        m6: 'ОРК',
        proj_result: '<strong>Жоба белгіленген мерзімде сәтті аяқталды</strong>, орындалған жұмыстардың жоғары сапасы компанияның кәсібилігі мен сенімділігін растайды.',
        op1_title: 'Қазақтелеком АҚ-ның күрделі жөндеуі',
        op1_desc: 'Алматы қ., Панфилов к., 129 мекенжайы бойынша үй-жайларды күрделі жөндеудің толық кешені. Жабындарды өзгерту, инженерлік жүйелерді алмастыру және жаңартуды қоса.',
        op1_tag: 'Тапсырыс беруші: Қазақтелеком АҚ',
        op2_title: 'Жұмыстардың кең ауқымы',
        op2_desc: 'Қазақстанның ірі телеком-операторларымен жылдар бойы жұмыс тәжірибесі. Жұмыстар барлық құрылыс нормалары мен стандарттарына сәйкес орындалды.',
        op2_tag: 'Барлық құрылыс түрлері',
        op3_title: 'Икемді тәсіл',
        op3_desc: 'Тапсырыс берушінің талаптарына икемді тәсіл. Жұмыстар әр клиенттің талаптары мен стандарттарына қатаң сәйкес орындалады.',
        op3_tag: 'Кілт тапсыру принципімен',
        trends_label: 'Телекоммуникация нарығы',
        trends_title: 'ТОЖС саласының даму үрдістері',
        trends_desc: 'Қазақстан нарығының ауқымы мен перспективалары одан әрі өсу мүмкіндіктерін ашады.',
        trend1_title: 'GPON технологиясы',
        trend1_desc: 'Интернетке жоғары жылдамдықты қол жеткізу үшін GPON (Gigabit Passive Optical Network) технологиясына көшу.',
        trend1_adv: 'Артықшылықтары:',
        trend1_li1: 'Жылдамдығы 1 Гбит/с дейін',
        trend1_li2: 'Белсенді жабдықтың аз мөлшері',
        trend1_li3: 'Қызмет көрсету шығындарын азайту',
        bsc_txt: 'үй шаруашылығы Қазақстанда GPON-ға қосылу мүмкіндігіне ие',
        trend2_title: 'Өткізу қабілеттілігін арттыру',
        trend2_desc: 'Өткізу қабілеттілігін 400–800 Гбит/с және одан жоғарыға дейін арттыру арқылы желілерді жаңарту.',
        trend2_fut: 'Болашақ:',
        trend2_li1: '1.2–1.6 Тбит/с-қа көшу',
        trend2_li2: 'Бұлттық қызметтерді қолдау',
        trend2_li3: 'ЖС мен Big Data инфрақұрылымы',
        ftth_desc: 'Жоғары жылдамдықты қол жеткізуді қамтамасыз ету үшін FTTH (Fiber to the Home) желілерін белсенді дамыту — үйге дейінгі талшық.',
        partner_label: 'Негізгі серіктестік',
        partner_title: 'Қазақтелекоммен серіктестік',
        partner_desc: 'Қазақстанның ең ірі телеком-операторы. Қазақтелеком — жұмыс сапасы мен бақылаудың ең қатаң стандарттары бар компания.',
        pkpi1: 'Нарық үлесі',
        pkpi2: 'Млн абонент',
        pkpi3: 'Елде бірінші',
        why_choose: 'Неге бізді таңдайды:',
        pr1_title: 'Сапаға ең жоғары талаптар',
        pr1_desc: 'Қазақтелеком сапа мен бақылаудың ең қатаң стандарттарын қолданады — біздің жұмыстарымыз оларға толықтай сәйкес келеді.',
        pr2_title: 'Көшбасшының сенімі',
        pr2_desc: 'Қазақтелекоммен серіктестік — мердігер ретінде кәсібилігіміз бен сенімділігіміздің ең жақсы растауы.',
        pr3_title: 'Мерзімдерді сақтау',
        pr3_desc: 'Ірі жобаларды белгіленген мерзімде сәтті іске асыру — SWAP жобасы оның дәлелі.',
        pr4_title: 'Сенімділік және кәсібилік',
        pr4_desc: 'Жылдар бойғы серіктестік сыналған мердігер ретінде сенімділігімізді растайды.',
        why_label: 'Серіктестіктің артықшылықтары',
        why_title: 'Неліктен ITStroyService?',
        why_desc: 'Қазақстанның жетекші операторлары бізді мердігер ретінде таңдайтын алты негізгі себеп.',
        why1_title: 'Заманауи жабдықтар',
        why1_desc: 'Кез келген күрделіліктегі жұмыстарды тиімді орындау үшін соңғы буын арнайы техника мен автопарк.',
        why2_title: 'Сыналған тәжірибе',
        why2_desc: 'Қазақтелеком үшін ірі жобаларды сәтті іске асыру, оның ішінде 692 км ТОЖС көлеміндегі SWAP жобасы.',
        why3_title: 'Барлық лицензиялар',
        why3_desc: 'Телекоммуникациялық және құрылыс жұмыстарын орындауға қажетті барлық лицензиялар (ҚСЖ 1 кат., Жобалау 1 кат., Іздестіру).',
        why4_title: 'Білікті команда',
        why4_desc: 'Телекоммуникациялық салада жылдар бойы тәжірибесі бар 100+ кәсіби маман.',
        why5_title: 'Толық қызмет циклі',
        why5_desc: 'Жобалаудан пайдалануға берілгенге дейін — «кілт тапсыру» принципімен жұмыстардың толық кешені (ЖЖЖ + ҚСЖ).',
        why6_title: 'Бәсекелестік бағалар',
        why6_desc: 'Тапсырыс берушінің барлық техникалық талаптарын сақтай отырып, баға мен сапаның оңтайлы қатынасы.',
        contact_label: 'Байланыс',
        contact_title: 'Ынтымақтастыққа дайынбыз',
        contact_desc: 'ITStroyService — телекоммуникациялық инфрақұрылымды дамытудағы сенімді серіктесіңіз.',
        c_addr_lbl: 'Мекенжай',
        c_addr: 'Астана қ., Қазақстан',
        c_email: 'Шартта көрсетілген',
        c_lic_lbl: 'Лицензиялар',
        c_lic: 'ҚСЖ 1 кат. · Жобалау 1 кат. · Іздестіру',
        ch_title: 'Күрделі міндеттер үшін бірыңғай мердігер',
        ch_desc: 'Физикалық инфрақұрылым мен цифрлық технологияларды біріктіреміз. Сапаның ең жоғары стандарттарына сәйкес жұмыс істейміз.',
        cp1: 'Кез келген күрделіліктегі ТОЖС құрылысы',
        cp2: 'Телекоммуникациялық инфрақұрылымды орналастыру',
        cp3: '«Кілт тапсыру» принципімен жұмыс — ЖЖЖ + ҚСЖ',
        cp4: 'Объектілерді күрделі жөндеу',
        cp5: 'Жол және инфрақұрылымдық құрылыс',
        cp6: 'Желілерге қызмет көрсету және жаңарту',
        footer_copy: '© 2025 ITStroyService. Барлық құқықтар қорғалған. Қазақстан.',
    },

    en: {
        nav_about: 'About',
        nav_services: 'Services',
        nav_projects: 'Projects',
        nav_partner: 'Partnership',
        nav_why: 'Advantages',
        nav_contact: 'Contact',
        nav_contact_footer: 'Contacts',
        hero_badge: 'Kazakhstan · All Licenses',
        hero_title: 'Reliable partner in<br><em>telecommunications</em> and<br>infrastructure construction',
        hero_sub: 'Trusted contractor for Kazakhstan\'s largest telecom operators. FOCL construction, infrastructure deployment and turnkey projects.',
        hero_location: 'Astana, Kazakhstan',
        hero_licenses: 'CW cat. 1 · Design cat. 1 · Surveys',
        hero_partner: 'Kazakhtelecom JSC Partner',
        hero_btn_projects: 'Our Projects',
        hero_btn_contact: 'Contact Us',
        stat1: 'Special equipment units',
        stat2: 'Professionals',
        stat3: 'Km of FOCL under SWAP',
        stat4: '% market share — Kazakhtelecom',
        about_label: 'About the Company',
        about_title: 'ITStroyService — Reliable Telecom Contractor',
        about_p1: 'The company specializes in construction and development of telecommunications infrastructure, as well as infrastructure and specialized construction in the Republic of Kazakhstan.',
        about_p2: 'We are a trusted contractor for the country\'s largest telecom operators.',
        feat1_title: 'Telecommunications',
        feat1_desc: 'FOCL construction, infrastructure deployment, network connections',
        feat2_title: 'Construction',
        feat2_desc: 'Infrastructure construction, turnkey projects, engineering design',
        feat3_title: 'Maintenance',
        feat3_desc: 'Network modernization, technical maintenance, repairs',
        feat4_title: 'Licenses',
        feat4_desc: 'CW cat. 1, Design cat. 1, Surveys — all required permits',
        resources_label: 'Company Resources',
        res1: 'Special Equipment',
        res1_unit: 'units',
        res2: 'Specialists',
        res2_unit: 'people',
        res3: 'Excavators, cable layers, bulldozers, low-loaders, pickups',
        res3_val: 'and more',
        res4: 'Key Client',
        res5: 'Licenses',
        res5_val: 'CW cat. 1<br>Design cat. 1<br>Surveys',
        svc_label: 'Service Areas',
        svc_title: 'Full Range of Services',
        svc_desc: 'Two main areas — telecommunications and infrastructure construction — cover the entire project cycle from design to commissioning.',
        svc1_title: 'Telecommunications & Communications',
        svc1_li1: 'Construction and development of fiber optic communication lines (FOCL) of any complexity',
        svc1_li2: 'Turnkey deployment of telecommunications infrastructure',
        svc1_li3: 'Connection of corporate and operator networks',
        svc1_li4: 'Maintenance and modernization of communication networks',
        svc2_title: 'Infrastructure Construction',
        svc2_li1: 'Construction of telecommunications industry facilities',
        svc2_li2: 'Road and infrastructure construction',
        svc2_li3: 'Design, installation and commissioning of facilities',
        svc2_li4: 'Turnkey projects — engineering surveys + construction, all licenses',
        proj_label: 'Completed Projects',
        proj_title: 'Large-scale Work<br>for Kazakhtelecom',
        proj_key: 'Key Project',
        proj_client: 'Client:',
        proj_desc: 'The project was implemented under the SWAP program for Kazakhstan\'s largest telecom operator — Kazakhtelecom JSC.',
        m1: 'Total FOCL length',
        m2: 'Backbone network',
        m3: 'Distribution network',
        m4: 'Installed poles',
        m5: 'Couplings',
        m6: 'ODF',
        proj_result: '<strong>The project was successfully completed on schedule</strong> with high quality work, confirming the professionalism and reliability of the company.',
        op1_title: 'Capital Renovation of Kazakhtelecom JSC',
        op1_desc: 'Full scope of capital renovation at the address: Almaty, Panfilov St., 129. Including finishing works, replacement of engineering systems and modernization.',
        op1_tag: 'Client: Kazakhtelecom JSC',
        op2_title: 'Wide Range of Works',
        op2_desc: 'Years of experience working with Kazakhstan\'s largest telecom operators. Works completed in accordance with all construction norms and standards.',
        op2_tag: 'All types of construction',
        op3_title: 'Flexible Approach',
        op3_desc: 'Flexible approach to customer requirements. Works are performed in strict accordance with the requirements and standards of each client.',
        op3_tag: 'Turnkey',
        trends_label: 'Telecom Market',
        trends_title: 'FOCL Industry Development Trends',
        trends_desc: 'The scale and prospects of the Kazakhstan market open broad opportunities for further growth.',
        trend1_title: 'GPON Technology',
        trend1_desc: 'Transition to GPON (Gigabit Passive Optical Network) technology for high-speed internet access.',
        trend1_adv: 'Advantages:',
        trend1_li1: 'Speeds up to 1 Gbit/s',
        trend1_li2: 'Fewer active equipment units',
        trend1_li3: 'Reduced maintenance costs',
        bsc_txt: 'households already have the technical capability to connect to GPON in Kazakhstan',
        trend2_title: 'Increasing Throughput Capacity',
        trend2_desc: 'Modernization of existing networks with increased throughput capacity up to 400–800 Gbit/s and above.',
        trend2_fut: 'Future:',
        trend2_li1: 'Transition to 1.2–1.6 Tbit/s',
        trend2_li2: 'Cloud services support',
        trend2_li3: 'Infrastructure for AI and Big Data',
        ftth_desc: 'Active development of FTTH (Fiber to the Home) networks — fiber to the home for high-speed access.',
        partner_label: 'Key Partnership',
        partner_title: 'Partnership with Kazakhtelecom',
        partner_desc: 'Kazakhstan\'s largest telecom operator. Kazakhtelecom is a company with the strictest quality and work control standards.',
        pkpi1: 'Market share',
        pkpi2: 'Mln subscribers',
        pkpi3: '#1 in country',
        why_choose: 'Why they choose us:',
        pr1_title: 'Highest Quality Standards',
        pr1_desc: 'Kazakhtelecom applies the strictest quality and control standards — our work fully meets them.',
        pr2_title: 'Trust of the Leader',
        pr2_desc: 'Partnership with Kazakhtelecom is the best confirmation of our professionalism and reliability as a contractor.',
        pr3_title: 'Meeting Deadlines',
        pr3_desc: 'Successful completion of large projects on schedule — the SWAP project is proof of this.',
        pr4_title: 'Reliability & Professionalism',
        pr4_desc: 'Years of partnership confirms our reliability as a trusted contractor.',
        why_label: 'Partnership Advantages',
        why_title: 'Why ITStroyService?',
        why_desc: 'Six key reasons why Kazakhstan\'s leading operators choose us as their contractor.',
        why1_title: 'Modern Equipment',
        why1_desc: 'Latest generation special equipment and modern fleet for efficient work of any complexity.',
        why2_title: 'Proven Experience',
        why2_desc: 'Successful implementation of large projects for Kazakhtelecom, including the SWAP project with 692 km of FOCL.',
        why3_title: 'All Licenses',
        why3_desc: 'All necessary licenses for telecommunications and construction work (CW cat. 1, Design cat. 1, Surveys).',
        why4_title: 'Qualified Team',
        why4_desc: '100+ professional specialists with years of experience in the telecommunications industry.',
        why5_title: 'Full Service Cycle',
        why5_desc: 'From design to commissioning — a complete turnkey package (surveys + construction).',
        why6_title: 'Competitive Prices',
        why6_desc: 'Optimal price-quality ratio while meeting all technical requirements of the customer.',
        contact_label: 'Contacts',
        contact_title: 'Ready to Cooperate',
        contact_desc: 'ITStroyService — your reliable partner in developing telecommunications infrastructure.',
        c_addr_lbl: 'Address',
        c_addr: 'Astana, Kazakhstan',
        c_email: 'Specified in contract',
        c_lic_lbl: 'Licenses',
        c_lic: 'CW cat. 1 · Design cat. 1 · Surveys',
        ch_title: 'Single Contractor for Complex Tasks',
        ch_desc: 'We combine physical infrastructure and digital technology. We work in accordance with the highest quality standards.',
        cp1: 'FOCL construction of any complexity',
        cp2: 'Deployment of telecommunications infrastructure',
        cp3: 'Turnkey projects — surveys + construction',
        cp4: 'Capital renovation of facilities',
        cp5: 'Road and infrastructure construction',
        cp6: 'Network maintenance and modernization',
        footer_copy: '© 2025 ITStroyService. All rights reserved. Kazakhstan.',
    }
};

// ===== LANGUAGE SWITCHER LOGIC =====
let currentLang = 'ru';

function applyLanguage(lang) {
    currentLang = lang;
    const t = translations[lang];
    if (!t) return;

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key] !== undefined) {
            el.innerHTML = t[key];
        }
    });

    // Update active button
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
    });

    // Update html lang attribute
    document.documentElement.lang = lang === 'kz' ? 'kk' : lang;
}

document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        const lang = btn.getAttribute('data-lang');
        applyLanguage(lang);
    });
});